GET http://localhost:4000/api/v1/users

###

POST http://localhost:4000/api/v1/users
content-type: application/json

{
   "username": "admin2",
   "password": "admin2@gmail.com",
   "email": "admin2@gmail.com",
   "fullname": "admin2"
}

###

GET http://localhost:3000/api/v1/students/2

###

POST http://localhost:3000/api/v1/students
content-type: application/json

{
   "name": "Rick",
   "email": "rick@gmail.com",
   "age": 34,
   "dob": "1983-12-31"
}

###

DELETE http://localhost:3000/api/v1/students/8

###

PUT http://localhost:3000/api/v1/students/7
content-type: application/json

{
   "name": "Rick"
}